/**
 * Copyright 2005-2010 Noelios Technologies.
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: LGPL 3.0 or LGPL 2.1 or CDDL 1.0 or EPL 1.0 (the
 * "Licenses"). You can select the license that you prefer but you may not use
 * this file except in compliance with one of these Licenses.
 * 
 * You can obtain a copy of the LGPL 3.0 license at
 * http://www.opensource.org/licenses/lgpl-3.0.html
 * 
 * You can obtain a copy of the LGPL 2.1 license at
 * http://www.opensource.org/licenses/lgpl-2.1.php
 * 
 * You can obtain a copy of the CDDL 1.0 license at
 * http://www.opensource.org/licenses/cddl1.php
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0.php
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://www.noelios.com/products/restlet-engine
 * 
 * Restlet is a registered trademark of Noelios Technologies.
 */

package microsoft.cloud.accesscontrol.management;


import java.util.Date;

import microsoft.cloud.accesscontrol.management.ServiceIdentity;


/**
* Generated by the generator tool for the OData extension for the Restlet framework.<br>
*
* @see <a href="https://cloudninjajava.accesscontrol.windows.net/v2/mgmt/service/$metadata">Metadata of the target OData service</a>
*
*/
public class ServiceIdentityKey {

    private String displayName;
    private Date endDate;
    private long id;
    private long serviceIdentityId;
    private Date startDate;
    private boolean systemReserved;
    private String type;
    private String usage;
    private byte[] value;
    private byte[] version;
    private ServiceIdentity serviceIdentity;

    /**
     * Constructor without parameter.
     * 
     */
    public ServiceIdentityKey() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public ServiceIdentityKey(long id) {
        this();
        this.id = id;
    }

   /**
    * Returns the value of the "displayName" attribute.
    *
    * @return The value of the "displayName" attribute.
    */
   public String getDisplayName() {
      return displayName;
   }
   /**
    * Returns the value of the "endDate" attribute.
    *
    * @return The value of the "endDate" attribute.
    */
   public Date getEndDate() {
      return endDate;
   }
   /**
    * Returns the value of the "id" attribute.
    *
    * @return The value of the "id" attribute.
    */
   public long getId() {
      return id;
   }
   /**
    * Returns the value of the "serviceIdentityId" attribute.
    *
    * @return The value of the "serviceIdentityId" attribute.
    */
   public long getServiceIdentityId() {
      return serviceIdentityId;
   }
   /**
    * Returns the value of the "startDate" attribute.
    *
    * @return The value of the "startDate" attribute.
    */
   public Date getStartDate() {
      return startDate;
   }
   /**
    * Returns the value of the "systemReserved" attribute.
    *
    * @return The value of the "systemReserved" attribute.
    */
   public boolean getSystemReserved() {
      return systemReserved;
   }
   /**
    * Returns the value of the "type" attribute.
    *
    * @return The value of the "type" attribute.
    */
   public String getType() {
      return type;
   }
   /**
    * Returns the value of the "usage" attribute.
    *
    * @return The value of the "usage" attribute.
    */
   public String getUsage() {
      return usage;
   }
   /**
    * Returns the value of the "value" attribute.
    *
    * @return The value of the "value" attribute.
    */
   public byte[] getValue() {
      return value;
   }
   /**
    * Returns the value of the "version" attribute.
    *
    * @return The value of the "version" attribute.
    */
   public byte[] getVersion() {
      return version;
   }
   /**
    * Returns the value of the "serviceIdentity" attribute.
    *
    * @return The value of the "serviceIdentity" attribute.
    */
   public ServiceIdentity getServiceIdentity() {
      return serviceIdentity;
   }
   
   /**
    * Sets the value of the "displayName" attribute.
    *
    * @param displayName
    *     The value of the "displayName" attribute.
    */
   public void setDisplayName(String displayName) {
      this.displayName = displayName;
   }
   /**
    * Sets the value of the "endDate" attribute.
    *
    * @param endDate
    *     The value of the "endDate" attribute.
    */
   public void setEndDate(Date endDate) {
      this.endDate = endDate;
   }
   /**
    * Sets the value of the "id" attribute.
    *
    * @param id
    *     The value of the "id" attribute.
    */
   public void setId(long id) {
      this.id = id;
   }
   /**
    * Sets the value of the "serviceIdentityId" attribute.
    *
    * @param serviceIdentityId
    *     The value of the "serviceIdentityId" attribute.
    */
   public void setServiceIdentityId(long serviceIdentityId) {
      this.serviceIdentityId = serviceIdentityId;
   }
   /**
    * Sets the value of the "startDate" attribute.
    *
    * @param startDate
    *     The value of the "startDate" attribute.
    */
   public void setStartDate(Date startDate) {
      this.startDate = startDate;
   }
   /**
    * Sets the value of the "systemReserved" attribute.
    *
    * @param systemReserved
    *     The value of the "systemReserved" attribute.
    */
   public void setSystemReserved(boolean systemReserved) {
      this.systemReserved = systemReserved;
   }
   /**
    * Sets the value of the "type" attribute.
    *
    * @param type
    *     The value of the "type" attribute.
    */
   public void setType(String type) {
      this.type = type;
   }
   /**
    * Sets the value of the "usage" attribute.
    *
    * @param usage
    *     The value of the "usage" attribute.
    */
   public void setUsage(String usage) {
      this.usage = usage;
   }
   /**
    * Sets the value of the "value" attribute.
    *
    * @param value
    *     The value of the "value" attribute.
    */
   public void setValue(byte[] value) {
      this.value = value;
   }
   /**
    * Sets the value of the "version" attribute.
    *
    * @param version
    *     The value of the "version" attribute.
    */
   public void setVersion(byte[] version) {
      this.version = version;
   }
   /**
    * Sets the value of the "serviceIdentity" attribute.
    *
    * @param serviceIdentity"
    *     The value of the "serviceIdentity" attribute.
    */
   public void setServiceIdentity(ServiceIdentity serviceIdentity) {
      this.serviceIdentity = serviceIdentity;
   }

}