//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class DiagnosticsConfig {
    
    private DiagnosticsConfigDirectories directoriesField;
    
    private DiagnosticsConfigPerformanceCounters performanceCountersField;
    
    private string storageAccountConnectionStringField;
    
    private int overallQuotaInMBField;
    
    public DiagnosticsConfig() {
        this.overallQuotaInMBField = 4096;
    }
    
    /// <remarks/>
    public DiagnosticsConfigDirectories Directories {
        get {
            return this.directoriesField;
        }
        set {
            this.directoriesField = value;
        }
    }
    
    /// <remarks/>
    public DiagnosticsConfigPerformanceCounters PerformanceCounters {
        get {
            return this.performanceCountersField;
        }
        set {
            this.performanceCountersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StorageAccountConnectionString {
        get {
            return this.storageAccountConnectionStringField;
        }
        set {
            this.storageAccountConnectionStringField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(4096)]
    public int OverallQuotaInMB {
        get {
            return this.overallQuotaInMBField;
        }
        set {
            this.overallQuotaInMBField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DiagnosticsConfigDirectories {
    
    private DiagnosticsConfigDirectoriesDirectory[] directoryField;
    
    private int scheduledTransferPeriodInSecondsField;
    
    public DiagnosticsConfigDirectories() {
        this.scheduledTransferPeriodInSecondsField = 60;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Directory")]
    public DiagnosticsConfigDirectoriesDirectory[] Directory {
        get {
            return this.directoryField;
        }
        set {
            this.directoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(60)]
    public int ScheduledTransferPeriodInSeconds {
        get {
            return this.scheduledTransferPeriodInSecondsField;
        }
        set {
            this.scheduledTransferPeriodInSecondsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DiagnosticsConfigDirectoriesDirectory {
    
    private string containerNameField;
    
    private string localPathField;
    
    private bool isLocalPathRelativeField;
    
    private int directoryQuotaInMBField;
    
    public DiagnosticsConfigDirectoriesDirectory() {
        this.isLocalPathRelativeField = false;
        this.directoryQuotaInMBField = 1;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ContainerName {
        get {
            return this.containerNameField;
        }
        set {
            this.containerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LocalPath {
        get {
            return this.localPathField;
        }
        set {
            this.localPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool IsLocalPathRelative {
        get {
            return this.isLocalPathRelativeField;
        }
        set {
            this.isLocalPathRelativeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(1)]
    public int DirectoryQuotaInMB {
        get {
            return this.directoryQuotaInMBField;
        }
        set {
            this.directoryQuotaInMBField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DiagnosticsConfigPerformanceCounters {
    
    private DiagnosticsConfigPerformanceCountersPerformanceCounter[] performanceCounterField;
    
    private int scheduledTransferPeriodInSecondsField;
    
    public DiagnosticsConfigPerformanceCounters() {
        this.scheduledTransferPeriodInSecondsField = 60;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PerformanceCounter")]
    public DiagnosticsConfigPerformanceCountersPerformanceCounter[] PerformanceCounter {
        get {
            return this.performanceCounterField;
        }
        set {
            this.performanceCounterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(60)]
    public int ScheduledTransferPeriodInSeconds {
        get {
            return this.scheduledTransferPeriodInSecondsField;
        }
        set {
            this.scheduledTransferPeriodInSecondsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class DiagnosticsConfigPerformanceCountersPerformanceCounter {
    
    private string counterNameField;
    
    private int samplingRateInSecondsField;
    
    public DiagnosticsConfigPerformanceCountersPerformanceCounter() {
        this.samplingRateInSecondsField = 10;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CounterName {
        get {
            return this.counterNameField;
        }
        set {
            this.counterNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(10)]
    public int SamplingRateInSeconds {
        get {
            return this.samplingRateInSecondsField;
        }
        set {
            this.samplingRateInSecondsField = value;
        }
    }
}
