/*******************************************************************************
 * Copyright 2012 Persistent Systems Ltd.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package com.microsoft.cloudninja.scheduler;

import java.net.URISyntaxException;
import java.security.InvalidKeyException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.TimeZone;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.util.StopWatch;

import com.microsoft.cloudninja.dao.MeteringDao;
import com.microsoft.cloudninja.dao.PartitionStatsAndBWUsageDao;
import com.microsoft.cloudninja.dao.TaskCompletionDao;
import com.microsoft.cloudninja.domainobject.MeteringEntity;
import com.microsoft.cloudninja.utils.SchedulerSettings;
import com.microsoft.cloudninja.utils.StorageClientUtility;
import com.microsoft.windowsazure.services.core.storage.StorageException;

/**
 * Processor for tenant DB size calculation task. It processes the
 * messages generated by generator.
 */
@Component
public class TenantDBSizeProcessor extends TaskActivityBase {
    
    @Autowired
    private TaskCompletionDao taskCompletionDao;
	
	private static final Logger LOGGER = Logger.getLogger(TenantDBSizeProcessor.class);
	
	@Autowired
	private MeteringDao meteringDao;
	
	@Autowired
	private PartitionStatsAndBWUsageDao partitionStatsAndBWUsageDao;
	
	public TenantDBSizeProcessor() throws InvalidKeyException, URISyntaxException {
		//tenantdbsizequeue which is shared between processor and generator.
		super(new TenantDBSizeQueue(SchedulerSettings.DatabaseSizeQueue, StorageClientUtility.getCloudStorageAccount().createCloudQueueClient()));
	}
	
	/** 
	 * Calculates DB size of tenant DB.
	 */
	@Override
	public boolean execute() {
	    
		boolean retVal = true;
		String tenantId = null;
		try {
		    
			LOGGER.debug("In Processor");
			long dbSize = 0;
			TenantDBSizeQueue queue = (TenantDBSizeQueue) getWorkQueue();
			tenantId = queue.dequeue(SchedulerSettings.MessageVisibilityTimeout);
			if (tenantId == null) {
				retVal = false;
				LOGGER.debug("Processor : msg is null");
			} else {
			    StopWatch watch = new StopWatch();
			    watch.start();
				LOGGER.debug("Processor : msg is " + tenantId);
				dbSize = partitionStatsAndBWUsageDao.getDBSize(tenantId);
				MeteringEntity metering = new MeteringEntity();
				metering.setTenantId(tenantId);
				
				Calendar calendar = Calendar.getInstance();
				SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.S z");
				dateFormat.setTimeZone(TimeZone.getTimeZone("UTC"));
				String date = dateFormat.format(calendar.getTime());
				metering.setSnapshotTime(dateFormat.parse(date));
				
				metering.setDatabaseSize(dbSize);
				meteringDao.add(metering);
				LOGGER.info("Processor : dbSize is " + dbSize);
				watch.stop();
	            taskCompletionDao.updateTaskCompletionDetails(watch.getTotalTimeSeconds(), "ProcessMeteringTenantDatabaseSize", "Measured "+dbSize+" for tenant "+tenantId+" database");
			}
		} catch (StorageException e) {
			retVal = false;
			LOGGER.error(e.getMessage(), e);
		} catch (ParseException e) {
			retVal = false;
			LOGGER.error(e.getMessage(), e);
		}
		return retVal;
	}

}
